# Generated by Django 4.2.5 on 2024-01-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
    ]
