# Generated by Django 4.2.5 on 2024-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_auto_20240117_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='msg',
        ),
        migrations.AddField(
            model_name='msg',
            name='mesg',
            field=models.TextField(default='no message sent'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='msg',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='msg',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
